<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Export Region</text>

        <Action name="dninosores_export_region">
            <icon></icon>
            <text>Export Region</text>
            <whatsThis>If part of the document is selected, export the selection. If nothing is
                selected, export everything in the current layer's bounding box.</whatsThis>
            <toolTip>If part of the document is selected, export the selection. If nothing is
                selected, export everything in the current layer's bounding box.</toolTip>
            <iconText></iconText>
            <activationFlags>1</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>alt+shift+e</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>